# fly.toml app configuration file generated for psi-dashboard-autumn-dawn-6422 on 2024-12-03T20:16:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'psi-dashboard-autumn-dawn-6422'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
